import { IEntries } from '../ShaderPuzzleCompletion';

export var spzeTagTable: IEntries = {
    color: {description: "color",},
    artist: {description: "artist",},
    init: {description: "init",},
    min: {description: "min",},
    max: {description: "max",},
    uigroup: {description: "uigroup",},
    uistep: {description: "uistep",},
    path: {description: "path",},
    name: {description: "name",},
    export: {description: "export",},
    addressu: {description: "addressu",},
    addressv: {description: "addressv",},
    addressw: {description: "addressw",},
    mip: {description: "mip",},
    mag: {description: "mag",},
    lodbias: {description: "lodbias",},
    thumbnail: {description: "thumbnail",},
    cache: {description: "cache",},
    default: {description: "default",},
    customizable: {description: "customizable",},
    instance: {description: "instance",},
};